### ISSUE TITLE
如果使用右键新窗口打开链接，就会导致访问出错

### ISSUE THREAD

**Issue by r-asou** [kirakiray/o-book#1]
单页面上点击没问题，但是右键新窗口访问，就不太行

https://kirakiray.github.io/o-book/website/ready.md
https://kirakiray.github.io/o-book/website/index.html#@obook/pages/reader/reader.js?path=docs/ready.md

**Comment by kirakiray** [comment]
相对 `index.html` 同目录，所以要加 `docs/`
https://kirakiray.github.io/o-book/website/docs/ready.md

**Comment by kirakiray** [comment]
已修正链接问题，现在右键打开是相应的 `md` 文件；
